---
gaming_packages:
  - steam
  - lutris
  - gamemode
  - mangohud
  - goverlay
  - gamescope
  - wine
  - winetricks
  - protontricks

gaming_extra_packages:
  - obs-studio

gaming_flatpak_packages:
  - net.davidotek.pupgui2
