---
- name: Install GStreamer codec plugins
  ansible.builtin.dnf5:
    name: "{{ multimedia_gstreamer_packages }}"
    state: present
  tags: multimedia

- name: Install FFmpeg
  ansible.builtin.dnf5:
    name: "{{ multimedia_extra_packages }}"
    state: present
  tags: multimedia

- name: Update multimedia group
  ansible.builtin.command:
    cmd: dnf5 groupupdate multimedia -y
  changed_when: true
  tags: multimedia

- name: Update sound-and-video group
  ansible.builtin.command:
    cmd: dnf5 groupupdate sound-and-video -y
  changed_when: true
  ignore_errors: true
  tags: multimedia
