---
nvidia_driver_packages:
  - akmod-nvidia
  - xorg-x11-drv-nvidia
  - xorg-x11-drv-nvidia-cuda
  - xorg-x11-drv-nvidia-cuda-libs

nvidia_support_packages:
  - nvidia-vaapi-driver
  - libva-utils
  - vdpauinfo
