---
base_cli_packages:
  - git
  - curl
  - wget
  - htop
  - btop
  - unzip
  - tar
  - vim
  - tmux
  - fastfetch
  - jq

enable_os_prober: false

firewall_allow_ssh: false
firewall_allow_rdp: false
firewall_tcp_ports: []

base_rpmfusion_free_key_url: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
base_rpmfusion_nonfree_key_url: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"
