---
- name: Install gaming packages
  ansible.builtin.dnf5:
    name: "{{ gaming_packages }}"
    state: present
  tags: gaming

- name: Install extra gaming packages
  ansible.builtin.dnf5:
    name: "{{ gaming_extra_packages }}"
    state: present
  tags: gaming

- name: Install gaming Flatpak packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  loop: "{{ gaming_flatpak_packages }}"
  tags: gaming
