---
multimedia_gstreamer_packages:
  - gstreamer1-plugins-base
  - gstreamer1-plugins-good
  - gstreamer1-plugins-bad-free
  - gstreamer1-plugins-bad-freeworld
  - gstreamer1-plugins-ugly
  - gstreamer1-plugin-libav

multimedia_extra_packages:
  - ffmpeg-libs
